concurrency:
  group: auto-scrape
  cancel-in-progress: true

name: Auto Scrape HackMyVM Achievements

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-action"
          git add data/achievements.csv
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update achievements.csv"
            git pull --rebase
            git push
          fi
